Cadastro do Autor, Excpetions e testes
Phillips-MF/e-digi pull request #1
Opened 2020-05-05 18:41 UTC by Phillips-MF

Dessa vez vai

2020-05-07 21:21 UTC, geovaniggr requested changes

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	static List<Autor> listaAutores = new ArrayList();
Qual o modificador de acesso dessa lista ?

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +}
Nos pilares de código do Alberto, temos 2 pontos importantes:

> Protegemos as bordas do sistema como se não houvesse amanhã.

Precisamos proteger a borda do sistema, aqui se decidirmos criar um autor com dados nulos, podemos, porque a validação não pertence a classe Autor, e sim outra classe

> Usamos o construtor para criar o objeto no estado válido.

Então acredito que é uma boa que o próprio autor saiba validar suas informações e o Sistema ser responsável apenas por adicionar :)

https://github.com/asouza/pilares-design-codigo

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	public void Adiciona(String nome, String email) throws NomeVazioException, EmailInvalidoException, EmailIgualException {
Acredito que aqui poderia ser `adiciona` para manter a consistência de nome de métodos

E se a nossa classe tem um nome genérico como `Sistema` como eu posso saber que o método adiciona está se referindo a um Autor?

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +		Autor autor = new Autor(nome, email);
Acredito que não faz sentido criar um Autor e depois validar as informações, o contrário sim!

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	public List<Autor> getAutores() {
Temos um outro pilar do Alberto:

> A versão mais eficiente de uma pessoa programando é aquela que entende, questiona e implementa estritamente o que foi combinado. Não inventamos coisas que não foram pedidas, não fazemos suposição de funcionalidade

Fazer uma listagem de autores é legal, mas nesse momento ainda não foi pedido nada assim

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +			System.out.println(autor.getNome() + " | " + autor.getEmail());
Acredito que podemos sobrescrever um método na classe Autor que faz a mesma coisa que você fez aqui :)
E de quebra tiramos a necessidade de existir um `getNome` ou `getEmail` nessa etapa

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	private boolean verificaNome(String nome) throws NomeVazioException {
Eu não entendi a razão do método devolver um valor `booleano`, não tem muita carga semântica o valor `true` ou `false` para verificaNome, e também não utilizamos o retorno do método para nada, então acredito que poderia ser um método vazio :)

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +		if (nome.isEmpty()) {
Essa sua validação consegue pegar strings vazias, mas falha caso o usuario passe `null` :)

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +		for (Autor autor : listaAutores) {
Será que um ArrayList não tem nenhum método para verificar se um elemento está dentro dele?

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +			if(autor.getEmail().equals(email)) {
Aqui está certinho a forma de comparar as strings, mas acredito que é papel do autor saber dizer o que é um autor ser "igual" a outro :)

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/testes/CadastroDeAutor.java
> +}
Que tal ao invés de criar um main para cada teste utilizarmos o `try_catch` ? Dessa maneira criamos apenas uma classe de teste do Autor :)

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	private boolean verificaEmailIgual(String email) throws EmailInvalidoException, EmailIgualException {
O seu método diz que pode lançar uma exceção de EmailInvalidoException, mas em nenhum momento isso parece ocorrer

2020-05-07 21:21 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/exceptions/EmailIgualException.java
> +}
Será que precisamos de exceções tão específicas? Dessa forma teremos métodos que lançaram vários tipos de exceções do tipo `checked` e em nenhum momento estamos tratando, acredito que podemos acabar o fluxo do programa quando temos um dado invalido :)

Sinto que estamos sempre lançando uma exceção quando os parâmetros passados são invalidos,  o java não tem nenhuma exceção padrão para isso ?

2020-05-20 19:39 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Sistema.java
> +	static List<Autor> listaAutores = new ArrayList();
Já resolvido

2020-05-20 20:46 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +}
Certo entendi, passei essa informações para essa classe

2020-05-25 11:53 UTC, geovaniggr requested changes

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +	}
A implementação do `equals` gerado pelas IDE's são bem úteis, mas elas são completamente generalistas :)

Aqui temos diversas comparações que não tem muito sentido, por exemplo, existe alguma chance de o `email` tanto do autor, quanto do autor comparado ser nulo ?

E o `email.equals` já retorna um booleano, podemos utilizar esse resultado para não colocar mais um `if` :)

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +	}
Durante todo o seu código não utilizamos esses dois `getters`, acredito que não há necessidade

O único comento que aparece em seu código é para imprimir as informações do autor, e podemos sobrescrever um método na classe autor, correto? :)

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/controllers/AutorController.java
> +}
Nesse momento do projeto não precisamos pensar em um arquitetura MVC, apenas o Autor e o AutorDAO já fazem sentido sozinhos

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/dao/AutorDao.java
> +	public void adicionaAutor(Autor autor) {
Diferente da classe "Sistema" que era muito genérica e precisava de nome que indicavam bem o que ela fazia, aqui temos a situação contrária, a classe "AutorDao" já indica que todos os métodos estão relacionados com o Autor, então podemos simplificar os nomes deles

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/dao/AutorDao.java
> +	private static List<Autor> listaAutores = new ArrayList<>();
Boa! Você já pegou a ideia de como utilizar os próprios métodos de Collections para deixar o código mais simples, agora acredito que podemos trocar esse `ArrayList` por uma outra coleção que não aceite elementos repetidos, dessa forma não precisamos do método "existeAutor" pois a própria inserção dirá se já existe ou não :)

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/exceptions/AutorJaExisteException.java
> +}
Você vê necessidade dessa exceção? Para mim um autor repetido se encaixa muito bem em uma `IllegalArgumentException`

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +		validaEmail(email);
Achei legal a ideia de criar uma função para evitar o mesmo código várias vezes, mas acho que isso vai deixar o código um pouco mais poluído, na medida em que nosso construtor vai ficar cheio de funções de validação, acredito que a ideia de validar por meio de um `setNome` `setEmail` e dentro de cada um ter uma lógica específica ( ainda que repetida ) é mais válido

2020-05-25 11:53 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/testes/TestaEmailInvalido.java
> +		Autor autor = new Autor("Carlos", "carlos2gmail.com");
Aqui acho que podemos trabalhar com um:
```
try {
.....
} catch ( IllegalArgumentException erro) {
System.out.println(erro.message());
}
``` 
Dessa maneira você consegue validar todos os testes em um mesmo arquivo, ao invés de ter uma classe para apenas 1 linha de código :)

2020-06-15 18:24 UTC, geovaniggr requested changes

2020-06-15 18:24 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/dao/AutorDao.java
> +			listaAutores.add(autor);
Qual o retorno de `listaAutores.add(autor)`? 

Penso que não precisamos desse `jaExiste` :)

2020-06-15 18:24 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
> +	}
Você não está usando isso em nenhum lugar :)

2020-06-17 19:40 UTC, geovaniggr approved these changes

2020-06-30 19:15 UTC, merged