Criação de categorias e testes de validação.
Phillips-MF/e-digi pull request #2
Opened 2020-06-30 19:56 UTC by Phillips-MF

2020-07-01 00:20 UTC, geovaniggr requested changes
Apenas algumas pequenas mudanças para deixar o código mais consistente, mas já está no caminho certinho!

2020-07-01 00:20 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Categoria.java
> +				return false;
Aqui temos aquele ponto que comentamos:

- Há possibilidade `nome` ser nulo?
- Há possibilidade `other.nome` ser nulo ? 

Podemos reduzir essa quantidade de `ifs`:)

2020-07-01 00:20 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Categoria.java
> +	private  final Instant criadoEm;
Opa, bom ponto, faltou isso na classe autor né?

2020-07-01 00:20 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/dao/CategoriaDao.java
> +	private Set<Categoria> listaCategorias = new HashSet<>();
Aqui por motivos de consistência, podemos deixar o `Set` estático da mesma maneira como feito no autor

2020-07-01 00:20 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/dao/CategoriaDao.java
> +		if(!listaCategorias.add(categoria)) {
Dado que você iremos transformar em estático, aqui existe algo que esqueci de te avisar, dado que trabalharemos com algo estático, é comum utilizarmos o nome da classe antes para deixar claro que é algo da classe, por exemplo:

```
CategoriaDao.listaCategorias.add(categoria);
```

2020-07-01 00:20 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Categoria.java
> +		return true;
Aqui também podemos aproveitar o retorno booleano do `nome.equals(other.nome)`

2020-07-01 11:19 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Categoria.java
> +	private  final Instant criadoEm;
Se não existe nada que indique que o nome da categoria ou do autor são mutáveis, por que não colocar final em todos?

2020-07-31 13:41 UTC, geovaniggr submitted a review, later dismissed
Faltou adicionar o instante no Autor também, após cadastrar

2020-07-31 13:41 UTC, geovaniggr commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Porque o `email` não ficou `final` também?
Agora um ponto que é importante saber, qual a motivação para colocar os campos `final`?

2020-07-31 14:40 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
O operador `final` utilizado junto com um atributo faz com que seu valor não possa ser alterado. Levando isso em consideração, o nome de um Autor() é apenas um, porém ele pode possuir mais de um email portanto seria necessário deixar esse atributo "aberto" para sofrer alterações. Da mesma forma a Classe Categoria() possui seus dois atributos como final pois uma categoria possui apenas um nome e o momento em que ela é criada é apenas um.

2020-08-02 13:22 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Esses são comportamentos que não estão descritos nas atividades dos cards, então você assumiu que seria assim que funcionaria, por isso a questão é relevante: se um é final, por que não são todos final? O que justifica um ser final ou não? É uma coisa que você assumiu ou é uma regra de negócio?

2020-08-03 18:04 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Quando eu estava realizando essas alterações, eu percebi que utilizar o final em alguns atributos seria algo lógico à se fazer, para que eles não sofressem alteração. Não são todos os atributos que precisam possuir `final`, como é o caso do email. De fato o que eu fiz não é uma regra de negócio, mas é uma maneira de proteger o código para que possíveis brechas não fiquem abertas levando a possíveis problemas.

2020-08-04 12:12 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Me cite uma brecha que você está evitando com isso.

2020-08-05 18:03 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Ao utilizar o `final` está sendo descartada a possibilidade  de alteração do valor do nome, após ele ser definido na criação de um `Autor`.

2020-08-05 18:21 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Certo, então por que eu estou proibido de alterar meu nome, mas não meu email?

2020-08-06 17:41 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Realmente, não faz muito sentido isso. Eu estava tentando evitar criar um objeto que possuísse dados inconsistentes que acabei me precavendo demais utilizando esse final. As outras validações feitas dentro das Classes já fazem com que os Objetos tenham dados consistentes. Então realmente não é necessário, para esse caso. o uso do final no nome do Autor.
Agora porém fiquei com dúvida para o uso desse operador nesse projeto, no caso do nome Autor() tudo bem, ele possui suas validações, mas e para o nome da Categoria(), eu penso que não existe a necessidade de se mudar o nome de uma Categoria() , no caso dela, tudo bem esse operador estar lá ?

2020-08-06 19:02 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
O uso do final não tem relação com dados inconsistentes, então, não houve prevenção. 

Em qualquer lugar, esse problema se aplica, o uso ou não do final, não tem relação com a consistência dos dados, mas sim com a estratégia de trabalhar com dados imutáveis ou não. O problema é o mesmo, os lugares podem ser diferentes.

2020-08-06 21:42 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Então eu realmente confundi o uso do `final`, eu achei que como o nome não é algo que comumente é alterado, não teria problema deixa-lo como final, dessa forma não teria como alguém alterar o nome de algum Autor que já tinha sido previamente criado, porém também acabei impossibilitando uma situação onde o nome concensualmente tivesse que ser alterado e como é comum alguém possuir mais de um email achei que poderia deixa-lo sem esse operador para que ele pudesse ser alterado. 
A minha dúvida ainda persiste em relação ao uso desse operador. Se eu retirar o final da classe Autor(), eu também teria que fazer o mesmo com todos os atributos dessa classe e das outras ? Porque a classe Categoria(), por exemplo, seria mais válido deixar o seu nome mutável ? Se sim por que ?

2020-08-07 12:02 UTC, wandersonmaceds commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
1. Não necessariamente, mas neste caso, Sim.
2. Não é uma questão da válido ou inválido, mas você precisa escrever o que a regra de negócio pede e não ficar imaginando situações aleatórias, se algo fosse pra ser imutável, estaria descrito em algum lugar. A minha pergunta inicial era sobre a razão de você usar o operador final em um atributo tão simples como o nome do Autor e não em outros. 
3. As Strings no Java se não me engano, já possuem um comportamento imutável, tanto que os métodos que alteram a string, te retornam uma nova string e não alteram a string original. O objeto pode ser re-atribuído, mas não alterado internamente. O final neste caso, só impede que seja re-atribuído, mas isso pode ser resolvido simplesmente pedindo o atributo pelo construtor, ele sendo privado, sem um set público relacionado a ele. Simples!

2020-08-12 19:42 UTC, Phillips-MF commented on e-digi/src/br/com/caelum/editora/modelos/Autor.java
>  	private String email;
Entendi agora, vou retirar então os finals das classes e prestar mais atenção nas regras de negócio.

2020-08-13 18:40 UTC, wandersonmaceds approved these changes

2020-08-14 15:36 UTC, merged